# Generated by Django 4.2.15 on 2024-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name='полное описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='краткое описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=1, verbose_name='широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.FloatField(default=1, verbose_name='долгота'),
            preserve_default=False,
        ),
    ]
