# Generated by Django 4.2.15 on 2024-08-12 18:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_id'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_short',
        ),
        migrations.AddField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='полное описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='краткое описание'),
        ),
    ]
